<div align="center"><h1><b><font size="6">
  BOLIVIAN ENERGY DEMAND</h1></font></div>
<div align="center"><h2><b><font size="5">
  END-USE DEMAND PROJECTIONS BY SECTOR AND TYPE OF USAGE (2021-2050)
</h2></font></b></div>

---

<div align="center"><h3><font size="3">
  <b> Developers:</b> Carlos Fernandez Vazquez, Pablo Jimenez Zabalaga
</h3></font></div>

---

<font size="5"><b>Growth expectations (BAU trends)</b></font>

<div align="justify">

The main assumption considered for projecting demands into the future under BAU conditions is that in Bolivia, energy consumption is heavily linked to population and economic values due to it being a developing country which growth hasn't reach a plateau.
Trends considered for this pourpose are population growth, yearly index of volume of sales and yearly mining exports.</div>

<font size="5"><b>Population growth expectations</b></font>

<div align="justify">The input data for the Bolivian expected growth has been directly taken from the National Insitute of Statistics (INE) of Bolivia which has made projections until 2050 following an stable growth. Original data should be found at these sources:
  <a href='https://www.ine.gob.bo/index.php/censos-y-proyecciones-de-poblacion-sociales/'>www.ine.gob.bo</a> or <a href='https://nube.ine.gob.bo/index.php/s/fyeHKHO9Zaeep2y/download'> direct_download_link</a></div>

In [1]:
# Import libraries
import pandas as pd

In [2]:
# # Option1: Upload manually the Excel file (available in the same folder of this notebook)
# # Read the Excel file into a Pandas DataFrame
# df_population = pd.read_excel(file_name, header=0, engine='openpyxl')
# #df

In [6]:
# Option2: Import the Google Drive Excel file
google_drive_url = 'https://docs.google.com/spreadsheets/d/1-SlyGkHA7MlvGr0LI5y6QGOx65d7fmUt/edit?usp=drive_link&ouid=115521570694102221364&rtpof=true&sd=true'
# Find the index of '/edit'
edit_index = google_drive_url.find('/edit')
# Remove all text after '/edit' (including '/edit')
google_drive_url = google_drive_url[:edit_index]
# Append '/export' to the cleaned URL
google_drive_url = google_drive_url + '/export'
# Read the Excel file into a Pandas DataFrame
df_population = pd.read_excel(google_drive_url, header=0, engine='openpyxl')
styled_df = df_population.style.hide()
styled_df

<font size="5"><b>Mining sector growth expectations</b></font>

<div align="justify">The input data for the Bolivian mining sector has been taken from the National Insitute of Statistics (INE) of Bolivia which has the total metric tons exported each year for the period 1990-2020. Exports registered consider the most exploited minerals in Bolivia (Sn, Cu, Pb and Zn). Original data should be found at these sources:
  <a href='https://www.ine.gob.bo/index.php/estadisticas-economicas/hidrocarburos-mineria/mineria-cuadros-estadisticos/'>www.ine.gob.bo</a> or <a href='https://nube.ine.gob.bo/index.php/s/f8Iw1MPCtTcpFT1/download'> direct_download_link</a></div>

In [4]:
# # Option1: Upload manually the Excel file (available in the same folder of this notebook)
# # Read the Excel file into a Pandas DataFrame
# df_historic_mining = pd.read_excel(file_name, header=0, engine='openpyxl')
# #df

In [7]:
# Option2: Import the Google Drive Excel file
google_drive_url = 'https://docs.google.com/spreadsheets/d/12MgHbauiUNRvvnQqa2z7tjTqyLfIJ1a1/edit?usp=drive_link&ouid=115521570694102221364&rtpof=true&sd=true'
# Find the index of '/edit'
edit_index = google_drive_url.find('/edit')
# Remove all text after '/edit' (including '/edit')
google_drive_url = google_drive_url[:edit_index]
# Append '/export' to the cleaned URL
google_drive_url = google_drive_url + '/export'
# Read the Excel file into a Pandas DataFrame
df_historic_mining = pd.read_excel(google_drive_url, header=0, engine='openpyxl')
styled_df = df_historic_mining.style.hide()
styled_df

In [8]:
import pandas as pd
from sklearn.linear_model import LinearRegression

# Option 1: this function is used to create a linear trend based on the latest years (15) with data available
#This trend is later used to project the exports per mineral in the future
def linear_projection(df, mineral_name, target_year):
    # Select the columns for the specified mineral and the year column
    data = df[['Year', mineral_name]]

    # Filter data for the last XYZ years
    last_years = data.tail(20)

    # Prepare the data for linear regression
    X = last_years[['Year']]
    y = last_years[mineral_name]

    # Create and fit the linear regression model
    model = LinearRegression()
    model.fit(X, y)

    # Make projections until the target year
    projections = pd.DataFrame({'Year': range(2020, target_year + 1)})
    projections[mineral_name] = model.predict(projections[['Year']])

    return projections

In [10]:
# Example usage:
# Assuming df is your DataFrame containing the data
# mineral_name is one of 'Sn', 'Cu', 'Pb', or 'Zn'
# target_year is the year until which you want to make projections
df = df_historic_mining
mineral_name = 'Tin Ore'  # Example mineral
target_year = 2050  # Example target year

projection_df = linear_projection(df, mineral_name, target_year)
styled_df = projection_df.style.hide()
styled_df

In [11]:
df_mining = pd.DataFrame({'Year': range(2020, 2050+1)})
minerals_list = ['Tin Ore', 'Copper Ore', 'Lead Ore', 'Zinc Ore']
for mineral in minerals_list :
  df_mining[mineral] = linear_projection(df_historic_mining, mineral, 2050)[mineral]
styled_df =  df_mining.style.hide()
styled_df

<font size="5"><b>Industry sector growth expectations</b></font>

<div align="justify">The input data for the Bolivian mining sector has been taken from the National Insitute of Statistics (INE) of Bolivia, which has the anual index of volume of sales compared to values in 1990 for the period 1990-2019.
This values represent the aggregated sales from the industrial manufacture sector and provide a rough understanding of the growth trend for the future. Original data should be found at these sources:
  <a href='https://www.ine.gob.bo/index.php/estadisticas-economicas/industria-manufacturera-y-comercio/estadisticas-coyunturales-cuadros-estadisticos/'>www.ine.gob.bo</a> or <a href='https://nube.ine.gob.bo/index.php/s/e4KGjnr2j1LPdi0/download'> direct_download_link</a></div>

In [12]:
# # Option1: Upload manually the Excel file (available in the same folder of this notebook)
# # Read the Excel file into a Pandas DataFrame
# df_historic_manufacture = pd.read_excel(file_name, header=0, engine='openpyxl')
# #df

In [14]:
# Option2: Import the Google Drive Excel file
google_drive_url = 'https://docs.google.com/spreadsheets/d/1U3iOSXakIp8-xR3TURzlccOjcfLMbouq/edit?usp=drive_link&ouid=115521570694102221364&rtpof=true&sd=true'
# Find the index of '/edit'
edit_index = google_drive_url.find('/edit')
# Remove all text after '/edit' (including '/edit')
google_drive_url = google_drive_url[:edit_index]
# Append '/export' to the cleaned URL
google_drive_url = google_drive_url + '/export'
# Read the Excel file into a Pandas DataFrame
df_historic_manufacture = pd.read_excel(google_drive_url, header=0, engine='openpyxl')
styled_df = df_historic_manufacture.style.hide()
styled_df

In [15]:
import pandas as pd
from sklearn.linear_model import LinearRegression

# Option 1: this function is used to create a linear trend based on the latest years (20) with data available
#This trend is later used to project the expected sales index in the future

def linear_projection(df, sales_index, target_year):
    # Select the columns for the specified mineral and the year column
    data = df[['Year', sales_index]]

    # Filter data for the last XYZ years
    last_years = data.tail(30)

    # Prepare the data for linear regression
    x = last_years[['Year']]
    y = last_years[sales_index]

    # Create and fit the linear regression model
    model = LinearRegression()
    model.fit(x, y)

    # Make projections until the target year
    projections = pd.DataFrame({'Year': range(2020, target_year + 1)})
    projections[sales_index] = model.predict(projections[['Year']])

    return projections

In [16]:
df = df_historic_manufacture
sales_index = 'Volume of Sales Index'
target_year = 2050

df_industry = linear_projection(df, sales_index, target_year)
styled_df = df_industry.style.hide()
styled_df

<font size="5"><b>Total End-Use demand per type of usage</b></font>

In [19]:
# Import libraries
import pandas as pd
#Import the Google Drive Excel file
google_drive_url = 'https://docs.google.com/spreadsheets/d/1sYqPcTcZpzuHsWliGDkYSn1ffy-YEqGG/edit?usp=drive_link&ouid=115521570694102221364&rtpof=true&sd=true'
# Find the index of '/edit'
edit_index = google_drive_url.find('/edit')
# Remove all text after '/edit' (including '/edit')
google_drive_url = google_drive_url[:edit_index]
# Append '/export' to the cleaned URL
google_drive_url = google_drive_url + '/export'
# Read the Excel file into a Pandas DataFrame
df_EUD = pd.read_excel(google_drive_url, header=0, engine='openpyxl')
styled_df = df_EUD.style.hide()
styled_df

In [23]:
list_sector = df_EUD['Sector'].unique().tolist()
list_subsector = df_EUD['Subsector'].unique().tolist()
list_class = df_EUD['Class'].unique().tolist()
list_usage = df_EUD['Type of usage'].unique().tolist()
list_technology = df_EUD['Technology'].unique().tolist()
list_usage

['Water Heating',
 'Cooking',
 'Food Preservation',
 'Space Heating',
 'Space Cooling',
 'Lighting',
 'Other Appliances',
 'Road',
 'Rail',
 'Water',
 'Air',
 'Water heating',
 'Machinery',
 'Process Heat',
 'Tractor & Others',
 'Irrigation',
 'High Temp Heat']

In [26]:
# Group by 'Usage' and aggregate 'End_Use_Demand' by sum
agg_df = df_EUD.groupby(['Sector', 'Subsector', 'Class', 'Type of usage', 'EUD units']).agg({'EUD': 'sum'}).reset_index()

styled_df = agg_df.style.hide()
styled_df

In [27]:
agg_df['EUD'].sum()

387886.8576456143

In [29]:
# Group by 'Usage' and aggregate 'End_Use_Demand' by sum
agg_df_2 = df_EUD.groupby(['Technology', 'Efficiency' ,'EUD units']).agg({'EUD': 'sum'}).reset_index()

# Specify the name of the Excel file
excel_file = "aggregated_data.xlsx"
agg_df_2.to_excel(excel_file, index=False, engine='openpyxl')

styled_df = agg_df_2.style.hide()
styled_df

In [30]:
def projected_EUD(EUD_DF_per_use, df_population, df_industry, df_mining, target_year):
    projected_df = EUD_DF_per_use.copy()  # Hacer una copia del DataFrame original
    # Definir los sectores directamente en listas para la comprobación
    sectors_population_based = ['Residential', 'Commercial', 'Public Lighting', 'Transport', 'Agriculture', 'Fishing & Others']

    # Iterar sobre cada fila del DataFrame
    for i, row in projected_df.iterrows():
        sector = row['Sector']
        subsector = row['Subsector']  # Usar 'Subsector' para la comprobación en el sector de minería
        current_value = row['EUD']

        # Comprobación para sectores basados en población
        if sector in sectors_population_based:
            current_projection = df_population[df_population['Year'] == 2021]['Population'].values[0]
            target_projection = df_population[df_population['Year'] == target_year]['Population'].values[0]
            projected_value = (current_value / current_projection) * target_projection
            projected_df.at[i, 'EUD'] = projected_value

        # Comprobación para el sector industrial
        elif sector == 'Industrial':
            current_projection = df_industry[df_industry['Year'] == 2021]['Volume of Sales Index'].values[0]
            target_projection = df_industry[df_industry['Year'] == target_year]['Volume of Sales Index'].values[0]
            projected_value = (current_value / current_projection) * target_projection
            projected_df.at[i, 'EUD'] = projected_value

        # Comprobación para el sector minero
        elif sector == 'Mining':
            # Lista de metales a comprobar
            metals = ['Tin Ore', 'Copper Ore', 'Lead Ore', 'Zinc Ore']
            # Verificar si el subsector corresponde a alguno de los metales
            if subsector in metals:
                metal = subsector  # El 'metal' específico se identifica directamente por el 'subsector'
                current_projection = df_mining[df_mining['Year'] == 2021][metal].values[0]
                target_projection = df_mining[df_mining['Year'] == target_year][metal].values[0]
                projected_value = (current_value / current_projection) * target_projection
                projected_df.at[i, 'EUD'] = projected_value

        # Si no se encuentra coincidencia, se deja el valor sin cambios

    return projected_df

In [31]:
# Estimate the total EUD per type of usage for a given year
projected_df = projected_EUD(agg_df, df_population, df_industry, df_mining, 2050)
styled_df = projected_df.style.hide()
styled_df

In [32]:
# Group by 'Usage' and aggregate 'End_Use_Demand' by sum
projected_df = projected_df.groupby(['Sector', 'EUD units']).agg({'EUD': 'sum'}).reset_index()

styled_df = projected_df.style.hide()
styled_df